name: Close associated issue

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub CLI with PAT
        run: |
          echo "${{ secrets.GIT_PAT }}" | gh auth login --with-token

      - name: Close associated issue
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
          PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GIT_PAT }}" $PR_URL | jq -r '.body')
          ISSUE_NUMBER=$(echo $PR_BODY | grep -oE "close #[0-9]+" | tr -d 'close #')
          if [[ ! -z "$ISSUE_NUMBER" ]]; then
            echo "Closing issue #$ISSUE_NUMBER"
            gh issue close $ISSUE_NUMBER --repo ${{ github.repository }}
          else
            echo "No issue number found in PR body."
          fi