name: Build and Push Docker Image

on:
  push:
    branches:
      develop
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 및 Gradle 환경 준비
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Java 배포판 (예: 'temurin' 또는 'zulu')
          java-version: '17'      # Java 버전 (예: '8', '11', '17')

      # 3. 스프링 부트 애플리케이션 빌드 (Gradle 사용)
      - name: Build Spring Boot application
        run: ./gradlew clean build -x test

      # 4. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest .

      # 6. Docker 이미지 푸시
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          

      # 5. EC2 인스턴스에 SSH로 접속하여 이미지 다운로드 및 컨테이너 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
            docker stop actions-test || true
            docker rm actions-test || true
            docker run -d --name actions-test -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest